# Generated by Django 2.1.5 on 2019-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='telegram_url',
            new_name='channel_url',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default='channel description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='channel_imgs'),
        ),
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.CharField(default='language', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='title',
            field=models.CharField(default='title', max_length=200),
            preserve_default=False,
        ),
    ]
