# Generated by Django 2.1.5 on 2019-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20190220_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='category',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
