# Generated by Django 2.1.5 on 2019-02-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_username',
            field=models.CharField(default='channel_url', max_length=200),
            preserve_default=False,
        ),
    ]
