# Generated by Django 2.1.5 on 2019-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_channel_channel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='channel',
            name='category',
            field=models.ForeignKey(on_delete={'r', 'e', 't', 'O', 'h'}, to='channels.Category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='language',
            field=models.ForeignKey(on_delete={'r', 'e', 't', 'O', 'h'}, to='channels.Language'),
        ),
    ]
