# Generated by Django 2.1.5 on 2019-04-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='sticker_images')),
                ('sticker_url', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete={'t', 'O', 'h', 'r', 'e'}, to='stickers.Category')),
            ],
        ),
    ]
